; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=T1GeracaoOS
AppVerName=T1GeracaoOS
AppPublisher=TChessIT
DefaultDirName={code:GetDefaultAddOnDir}
DisableDirPage=yes
Compression=lzma
SolidCompression=yes
UsePreviousAppDir=no
AppendDefaultDirName=yes
Uninstallable=yes
OutputDir="C:\Users\kuricaambiental_02\source\repos\ChessIT\ChessIT.GeracaoOS\Setup"
CloseApplications=force
OutputBaseFilename=setup
SourceDir="C:\Users\kuricaambiental_02\Source\Repos\ChessIT\ChessIT.GeracaoOS\ChessIT.GeracaoOS\bin\x64\Release"

[Files]
Source: ChessIT.GeracaoOS.exe; Flags: ignoreversion; DestDir: {app}
Source: ChessIT.GeracaoOS.exe.config; Flags: ignoreversion; DestDir: {app}
Source: *.dll; Flags: ignoreversion; DestDir: {app}
Source: SrfFiles\*; Flags: ignoreversion; DestDir: {app}\SrfFiles
Source: Menu.xml; Flags: ignoreversion; DestDir: {app}
Source: C:\Users\kuricaambiental_02\source\repos\ChessIT\ChessIT.GeracaoOS\Setup\AddOnInstallAPI.dll; Flags: dontcopy

;InformaciÃ³n para la desinstalaciÃ³n
[Registry]
Root: HKCU; Subkey: Software\TChessIT\ChessIT.T1GeracaoOS; Flags: uninsdeletekey
Root: HKLM; Subkey: Software\TChessIT\ChessIT.T1GeracaoOS; Flags: uninsdeletekey
Root: HKLM; Subkey: Software\TChessIT\ChessIT.T1GeracaoOS; ValueType: string; ValueName: InstallPath; ValueData: {app}

[Languages]
Name: Portugues; MessagesFile: compiler:Languages\BrazilianPortuguese.isl

[Code]
//-Public Vars
var
  CurrentLocation : string;
  AddOnDir : string;
  FinishedInstall : Boolean;
  Uninstalling : Boolean;

const
  ADDON_ID   = 'T1GeracaoOS';
  PARTNER_ID = 'TChessIT';

//-External Functions (AddOnInstallAPI.dll)
function EndInstall: integer; external 'EndInstall@files:AddOnInstallAPI.dll stdcall';
function SetAddOnFolder(srcPath : string): integer; external 'SetAddOnFolder@files:AddOnInstallAPI.dll stdcall';
function RestartNeeded :integer; external 'RestartNeeded@files:AddOnInstallAPI.dll stdcall delayload ';
function EndUninstall(path: string; succeed: boolean): integer; external 'EndUninstall@files:AddOnInstallAPI.dll stdcall';

//-Check if the application is installed;
//- if yes --> suggest to Remove
//- if no --> Install
function CheckInstalled(): boolean;
  var
    ResultCode: Integer;
  begin
    result := False;
    //-if find...
    if RegQueryStringValue(HKEY_LOCAL_MACHINE, 'SOFTWARE\' + PARTNER_ID + '\' + ADDON_ID,'InstallPath', CurrentLocation) then
      begin
        //-...Execute the uninstall to remove
        if FileExists(CurrentLocation + '\unins000.exe') then
          begin
            Exec(CurrentLocation + '\unins000.exe', '', '', SW_SHOW, ewWaitUntilTerminated, ResultCode)
            result := True;
          end;
      end;
  end;
 procedure UninstallCurrentVersion();
  var
    ResultCode: Integer;
  begin
    if RegQueryStringValue(HKLM, 'Software\TChessIT\TGeracaoOS\Management','InstallPath', CurrentLocation) then
      begin
        MsgBox('Pressione [OK] para remover a versão existente', mbInformation, MB_OK)
        //-...Execute the uninstall to remove
        Exec(CurrentLocation + '\unins000.exe', '', '', SW_SHOW, ewWaitUntilTerminated, ResultCode);
      end;
  end;
//-When Setup starts, get the parameters of B1
function PreparePaths() : Boolean;
  var
    position : integer;
    aux : string;
    ResultCode : Integer;
    cont : integer;
    Uninstall : boolean;
  begin
    Uninstall := false;
    if IsUninstaller then
      begin
        Result := True
      end
    else
      begin
        Result := False;
        for cont := 0 to ParamCount() do
          begin
            //MsgBox('Param(' + inttostr(cont) + ') = ' + paramstr(cont), mbInformation, MB_OK);
            if pos('|', paramstr(cont)) <> 0 then
              begin
                aux := paramstr(cont);
                position := Pos('|', aux)
                AddOnDir := Copy(aux,0, position - 1)
                Result := True;
                cont := ParamCount()+1
              end;
            if paramstr(cont) = '/u' then
              begin
                Uninstall := true;
              end;
          end;

        if Result = False then
          begin
            if Uninstall Then
              begin
                RegQueryStringValue(HKLM, 'Software\TChessIT\TGeracaoOS\Management','InstallPath', CurrentLocation)
                Exec(CurrentLocation + '\unins000.exe', '', '', SW_SHOW, ewWaitUntilTerminated, ResultCode);
                EndUninstall(CurrentLocation, true);
              end
            else
              begin
                MsgBox('O add-on só pode ser instalado apartir do SAP Business One.', mbError, MB_OK);
              end;
          end
        else
          begin
            UninstallCurrentVersion
          end;
      end;
  end;

function GetDefaultAddOnDir(Param : string): string;
  begin
    //-Default Directory to Install the Add-On
       result := AddOnDir;
  end;

function InitializeSetup(): Boolean;
  begin
    result := PreparePaths;
  end;

function NextButtonClick(CurPageID: Integer): Boolean;
  begin
    Result := True;
    case CurPageID of
      wpSelectDir :
        begin
          AddOnDir := ExpandConstant('{app}');
          end;
      wpFinished :
        begin
          //-If All OK then
          if FinishedInstall then
            begin
              //-Send to B1 the Installation Folder and ...
              SetAddOnFolder( ExpandConstant('{app}'));
              //-...indicates finish installing
              EndInstall();
            end;
        end;
    end;
  end;

procedure CurStepChanged(CurStep: TSetupStep);
  begin
    if CurStep = ssPostInstall then
      FinishedInstall := True;
    end;



